name: CI Playwright

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx playwright install

      - run: npx playwright test

      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman collection
        run: newman run ./postman/Test\ PM\ -\ PW\ et\ docker.postman_collection.json

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
